[package]
name = "typerd"
description = ""
readme = "README.md"
version = "0.1.0"

edition = "2021"
rust-version = "1.59"

[dependencies]
serde = { version = "1.0.136", optional = true, features = ["derive"] }

[dev-dependencies]
serde = { version = "1.0.132", features = ["derive"] }
